version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      #- aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - IMAGE_NAME="apidemo"
      - REPOSITORY_URI=328458102011.dkr.ecr.us-east-1.amazonaws.com/api-demo
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=prod_${COMMIT_HASH:=latest}
    #  - IMAGE_TAG=prod_$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - cd services
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - echo Image_tag $IMAGE_TAG
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Ho Gaya bhai push ecr dekh le
    #  - echo Writing image definitions file...
    #  - printf '[{"name":"apidemo-container","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
#artifacts:
#      files: imagedefinitions.json
